### ISSUE TITLE
Палитра и пипетка

### ISSUE THREAD

**Issue by Mmmaximus** [bmstu-iu9/ptp2021-3-vector-editor#10]

**Comment by Mmmaximus** [comment]
Перемещено в Projects

**Comment by Mazdaywik** [comment]
Кстати, в проекте можно наоборот, щёлкнуть на меню прямоугольника и выбрать «Convert to issue»:

![image](https://user-images.githubusercontent.com/1309859/127929839-6dc5fc22-4e65-49e4-a54d-d24ca709c211.png)

**Comment by mathhyyn** [comment]
закрываю задним числом)
