### ISSUE TITLE
Палитра

### ISSUE THREAD

**Issue by Mmmaximus** [bmstu-iu9/ptp2021-3-vector-editor#11]

**Comment by Mmmaximus** [comment]
Перемещено в Projects

**Comment by Mazdaywik** [comment]
Чтобы поместить задачу в проект, нужно слева выбрать проект. Вот сейчас выберу для примера.

**Comment by Mazdaywik** [comment]
И теперь посмотрите, что там находится в проектах.

**Comment by Mmmaximus** [comment]
Готово
