### ISSUE TITLE
разделить текущий на 2 css файла

### ISSUE THREAD

**Issue by mathhyyn** [bmstu-iu9/ptp2021-3-vector-editor#40]
В один положить все чётные селекторы, в другой — все нечётные.

**Comment by Mmmaximus** [comment]
Лучше распределить по местам, на которые селекторы влияют, например, header и main

**Comment by Mazdaywik** [comment]
> В один положить все чётные селекторы, в другой — все нечётные.

Это я прикололся (разве не заметно «edited by Mazdaywik»). При подобной постановке задачи лучше давать пояснение, по какому принципу разделять — что перенести в один, а что в другой. И, соответственно, как назвать оба файла.
